#!/bin/bash
# izsyncmysql: mysql database direct replicate/export/import script
# written by Ugo Viti <ugo.viti@initzero.it>
# version: 20220125

## Examples:

#**copy local database into other database:**
#  src_host='localhost' src_port=3306 src_username='root' src_password='PASSWORD' dst_host='localhost' dst_port=3306 dst_username='root' dst_password='PASSWORD' izsyncmysql DATABASE_SORGENTE DATABASE_DESTINAZIONE

#**mysql replica via tcp 3306 singolo DB (mantain source DB name):**
#  src_host='wms-database.prod.svc.cluster.local' src_port=3306 src_username='root' src_password='PASSWORD' dst_host='wms-database.test.svc.cluster.local' dst_port=3306 dst_username='root' dst_password='PASSWORD' izsyncmysql DATABASE_SORGENTE

#**mysql replica via tcp 3306 single DB (renaming the destination DB):**
#  src_host='wms-database.test.svc.cluster.local' src_username='root' src_password='PASSWORD' dst_host='wms-database.test.svc.cluster.local' dst_username='root' dst_password='PASSWORD' izsyncmysql DATABASE_SORGENTE DATABASE_DESTINAZIONE

#**mysql replica Tunnel SSH single DB (mantain source DB name):**
#  ssh=1 ssh_src_host="www.cloudwms.it" ssh_src_port="32" src_host='127.0.0.1' src_username='root' src_password='PASSWORD' dst_host='127.0.0.1' dst_username='root' dst_password='PASSWORD' izsyncmysql DATABASE_SORGENTE

#**mysql replica via Tunnel SSH of all DB and some excluded:**
#  ssh=1 ssh_src_username=initzero ssh_src_host="www.cloudwms.it" ssh_src_port="32" src_host='127.0.0.1' src_username='root' src_password='PASSWORD' src_db_exclude='-e information_schema -e performance_schema -e sys -e mysql' dst_host='127.0.0.1' dst_username='root' dst_password='PASSWORD' izsyncmysql


src_db="$1"
shift
dst_db="$1"
 
export_views=1
 
izsyncmysql_src_cfg="$HOME/izsyncmysql_src.cfg"
izsyncmysql_dst_cfg="$HOME/izsyncmysql_dst.cfg"

#set -x
 
: ${ssh:=0}
 
: ${ssh_src_host:=""}
: ${ssh_src_port:="22"}
: ${ssh_src_username:="root"}
 
: ${src_host:=""}
: ${src_username:="root"}
: ${src_password:=""}
: ${src_port:="3306"}
 
: ${src_db_exclude:="-e information_schema -e performance_schema -e sys -e mysql"}
 
: ${dst_host:=""}
: ${dst_username:="root"}
: ${dst_password:=""}
: ${dst_port:="3306"}
 
[[ -z "$ssh_src_host" ]] && ssh=0
[[ -z "$src_host" || -z "$src_username" ]] && echo "ERROR: no source host or username specified. exiting..." && exit 1
[[ -z "$dst_host" || -z "$dst_username" ]] && echo "ERROR: no destination host or username specified. exiting..." && exit 1
 
# save mysql src logins
echo "[client]
host=$src_host
port=$src_port
user=$src_username
$([ ! -z $src_password ] && echo password=$src_password)
" > "$izsyncmysql_src_cfg"

echo "[client]
host=$dst_host
port=$dst_port
user=$dst_username
$([ ! -z $dst_password ] && echo password=$dst_password)
" > "$izsyncmysql_dst_cfg"

# default mysqldump options
mysqldump_opts="-C --force --opt --quote-names --default-character-set=utf8 --events --routines --triggers --hex-blob --single-transaction --quick --lock-tables=false --column-statistics=0"
#mysqldump_opts+=" --hex-blob --skip-triggers --set-gtid-purged=OFF --default-character-set=utf8"
 
# add drop database if no src_db or dst_db is given
#if [[ -z "$dst_db" ]]; then
#    dst_db_drop=0
#    mysqldump_opts+=" -B --add-drop-database"
#  else
#    dst_db_drop=1
#fi
 
# show all database size
# SELECT table_schema AS "Database name", SUM(data_length + index_length) / 1024 / 1024 AS "Size (MB)" FROM information_schema.TABLES GROUP BY table_schema;
 
ssh_run() {
        #ssh -o BatchMode=yes -o StrictHostKeyChecking=no -C -n $ssh_src_username@$ssh_src_host -p $ssh_src_port "$@"
        ssh -o StrictHostKeyChecking=no -C -n $ssh_src_username@$ssh_src_host -p $ssh_src_port "$@"
}
 
mysql_query_src() {
        local dbname=$1
        shift
        local host=$src_host
        local port=$src_port
        local username=$src_username
        local password=$src_password
        mysql_query $izsyncmysql_src_cfg $dbname $@
}
 
mysql_query_dst() {
        local dbname=$1
        shift
        local host=$dst_host
        local port=$dst_port
        local username=$dst_username
        local password=$dst_password
        mysql_query $izsyncmysql_dst_cfg $dbname $@
}
 
mysql_query() {
        local extrafile=$1
        shift
        local dbname=$1
        shift
        local query="mysql --defaults-extra-file=$extrafile --batch --skip-column-names --raw '$dbname' --execute='$@' 2>&1"
        [ $ssh = 1 ] && ssh_run "$query" || eval $query
}
 
izsyncmysql() {
  if [ -z "$src_db" ]; then
    src_dblist="$(mysql_query_src mysql "SHOW DATABASES;" | grep -wv ${src_db_exclude} | tr -s "\n" " ")"
    [ $? != 0 ] && echo "ssh unable to connect" && exit 1
  else
    src_dblist="$src_db"
  fi
 
  n=1
  src_db_tot=$(echo "$src_dblist" | awk '{print NF}')
 
  [[ ! -z "$src_db" && -z "$dst_db" ]] && dst_db="$src_db"
 
  ssh_src_uri="ssh://$ssh_src_username@$ssh_src_host:$ssh_src_port"
  src_uri="mysql://$src_username@$src_host:$src_port/$src_db"
  dst_uri="mysql://$dst_username@$dst_host:$dst_port/$dst_db"
 
  echo "$(log) ----------------------------------------------"
  [ $ssh = 1 ] && echo "               Tunnel SSH: ssh://$ssh_src_username@$ssh_src_host:$ssh_src_port"
  echo "               Source URI: $src_uri"
  echo "          Destination URI: $dst_uri"
  echo
  echo "          Database totali: $src_db_tot"
  echo "Database da sincronizzare: $src_dblist"
  echo
  [ $src_uri = $dst_uri ] && echo -e "ERROR: you are cloning a DB into itself... exiting now to avoid data loss" && exit 1
  echo -e -n "Premere invio per continuare (CTRL-C per cancellare)"; read -n 1
  echo
  echo "$(log) ----------------------------------------------"
 
  for src_db in $src_dblist ; do
   [ $n -ne 1 ] && echo
   # if dst_db is not defined use the src_db name
   [ -z "$dst_db" ] && dst_db=$src_db
   local dbsize="$(mysql_query_src $src_db "SELECT table_schema \"Database Name\", ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) \"Database Size (MB)\" FROM information_schema.TABLES where table_schema = \"$src_db\";" | awk '{print $2}')"
   echo "$(log) [$n/$src_db_tot] START processing DB:[$src_db] size:[$dbsize MB]"

   #set -x
 
   # drop and recreate empty destination db if specified
   # if destination db exist, drop it before creating
   if [ ! -z "$(mysql_query_dst mysql "SHOW DATABASES LIKE \"$dst_db\";")" ]; then
     echo "$(log) => dropping destination DB:[${dst_uri}${dst_db}]"
     mysqladmin --defaults-extra-file=$izsyncmysql_dst_cfg drop "$dst_db" -f 2>&1 | grep -v '^Database.* dropped$'
   fi
   echo "$(log) => creating empty DB:[${dst_uri}${dst_db}]"
   mysqladmin --defaults-extra-file=$izsyncmysql_dst_cfg create "$dst_db"

   echo "$(log) => importing from source DB:[${src_uri}${src_db}]$([ $ssh = 1 ] && echo " (via $ssh_src_uri)") to destination DB:[${dst_uri}${dst_db}]"
   [ $export_views = 0 ] && mysql_viewlist="$(mysql_query_src $src_db "SHOW FULL TABLES IN $src_db WHERE TABLE_TYPE LIKE \"VIEW\";" | awk '{print $1}' | tr -s "\n" " ")"
 
   # export / import db single step
   [ $export_views = 0 ] && local mysqldump_opts_extra=" $(for view in $mysql_viewlist; do echo -n ' --ignore-table=$src_db.$view'; done)"
   local query_dump="mysqldump --defaults-extra-file=$izsyncmysql_src_cfg $mysqldump_opts $mysqldump_opts_extra $src_db"
   local query_import="mysql --defaults-extra-file=$izsyncmysql_dst_cfg -f $dst_db"
 
   unset sync_cmd
   [ $ssh = 1 ] && sync_cmd+="ssh_run "
   sync_cmd+="$query_dump "
   sync_cmd+="| sed -E -e 's/DEFINER=\`([^\`]+?)\`@\`([^\`]+?)\`/DEFINER=CURRENT_USER/g' -e 's/,NO_AUTO_CREATE_USER//g' "
   sync_cmd+="| $query_import "
   
   echo "$(log) => running query: $sync_cmd"

   eval $sync_cmd
 
   echo "$(log) [$n/$src_db_tot] END processing DB:[$src_db]"
   let n+=1
   # unset variables
   unset src_db dst_db sync_cmd mysqldump_opts_extra
   # wait 1 sec before proceding
   sleep 1
  done
  echo "$(log) ----------------------------------------------"
}
 
log() {
        echo "$(date +"[%Y/%m/%d %H:%M:%S]")$1 "
}
 
izsyncmysql

# if we no error occur, then cleanup all temporary files and directories
trap "rm -f "${izsyncmysql_src_cfg}" "${izsyncmysql_dst_cfg}" && exit 0 || exit 1" 0
